
apiVersion: v1
kind: Service
metadata:
  name: test-app
spec:
  selector:
    app: test-app
  ports:
    - port: 8080
      protocol: 'TCP'
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  replicas: 1
  template:
    metadata:
      name: test-app
      labels:
        app: test-app
    spec:
      containers:
        - name: test-app
          image: jahadulrakib/test_project:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: localhost
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: root
            - name: DB_NAME
              value: test_application
  selector:
    matchLabels:
      app: test-app